### ISSUE TITLE
Become a verified creator

### ISSUE THREAD

**Issue by nicorikken** [fsfe/reuse-action#11]
When allowing GitHub Actions from the level of a GitHub Organization, there is a default option to only allow actions by **verified creators**. As the fsfe is not a verified creator, it requires an explicit allow-list entry if wanting to enable it:

![image](https://user-images.githubusercontent.com/7458098/133612218-3bd08c7e-97af-48cf-8dfc-d700a9084d2d.png)

This is an unnecessary hurdle for the adoption of the reuse-action.

So it would be helpful if the GitHub FSFE organization would become a Verified Creator. More information can be found on the GitHub Marketplace documentation: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by mxmehl** [comment]
Thanks for the hint, I wasn't aware of this new hurdle.

I registered the FSFE organisation, it will have to be manually verified by GH.

**Comment by mxmehl** [comment]
The publisher verification was successful. However, I don't see a check on the marketplace app. Can you please somehow confirm that this fixed your issue?

**Comment by ferdnyc** [comment]
Not lookin' like things have come together yet. 

![image](https://user-images.githubusercontent.com/538020/135711667-0a76e975-b811-4c18-8198-73adc1c789fd.png)

Maybe you need to do a new release to get the status re-checked?

**Comment by ferdnyc** [comment]
It's very strange — if I activate that filter _without_ a search string, there are two subtly different kinds of checkmarked action. One type has the checkmark next to the publisher name, and the tooltip reads "Publisher domain and email verified". The other type has the checkmark next to the name of the **action**, and that mark carries a tooltip reading, "App meets the requirements for listing".

**Comment by ferdnyc** [comment]
@mxmehl I [took it to the forums](https://github.community/t/getting-verified-action-status-for-an-existing-action/205651) on your behalf. We'll see if anything comes of it.

**Comment by ferdnyc** [comment]
Hmm. I did just notice that, while the FSFE organization is listed as Verified, the releases are being made by _your_ personal account — which doesn't appear to be. I wonder if perhaps that's the issue? (I'm still guessing wildly, no question, so I wouldn't put too much faith in this unless there's some external evidence I may be having a stopped-clock episode.)

**Comment by ferdnyc** [comment]
@mxmehl  So, I have finally worked out the situation here, many months down the road. It has nothing to do with who publishes the releases, and everything to do with GitHub's rapid expansion (both pre- and post-Microsoft) turning it into a many-headed hydra of an Enterprise in the tradition of 1990s Sun Microsystems. (Showing my age.)

Turns out, GitHub _Apps_ can have "Verified Creators", and they are indicated by badges to that effect in the Marketplace.

For GitHub _Actions_, though, there's no such thing as a Verified Creator badge — only GitHub _**Partner**_ developers get badges on their Actions.

Both types of project are published through the same Marketplace, but the rules are completely different, because of course they are.

All that being said, the FSFE may well be eligible to become a GitHub Partner organization — specifically, a Technology Partner — and the process for applying to _that_ program appears to begin here: https://partner.github.com/technology-partners

**Comment by mxmehl** [comment]
Thank you so much for your research! Currently we do not plan to become a GitHub Partner organisation. I hope that enabling the action poses no problems apart from the confusion.

Closing now, but please feel free to reopen if there's new intel, or if this is a real problem for someone.
