### ISSUE TITLE
Should the action support versioning?

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-action#2]
Axiom: If the action is run twice on the same commit, it should *always* produce the same results.

However, fsfe/reuse-action@master cannot guarantee this. If we versioned the action (e.g., fsfe/reuse-action@0.8.0 uses reuse-tool@0.8.0), we *could* guarantee this.

Is this something we want to support?

**Comment by mxmehl** [comment]
Yeah, I thought that this will be brought up ;)

Github actions seem to support semantic versioning, so using "v1" will also make use of a release "v1.1". It might be that future versions of this action will be incompatible with older ones, e.g. if we find a better/other way to deal with multiple arguments.

However, I would not use the same version as the tool. For me, the action is an easy way to use reuse lint if people prefer GH actions. I would not want them to need to upgrade the action every time we release a new tool version, especially since we do not intend to introduce breaking changes. And even if, we could release a new major version of the action (see above). So yes, this would risk that the output may change slightly, but the exit code would not.

**Comment by jeremiah** [comment]
I think that being idempotent is a good thing, and versioning can help there. Glad to see the use of semantic versioning too and being separate from the overall tool's version. I hope that as much backwards compatibility can be kept as possible - stability is often a killer feature of an API or Action.

**Comment by mxmehl** [comment]
I consider this issue to be closed as we support `v1` now until a breaking change occurs.
